[2024-10-18T13:36:07.953+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:36:08.123+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-10-18T13:36:08.182+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2024-05-17T00:00:00+00:00 [queued]>
[2024-10-18T13:36:08.186+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:36:08.388+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_3rd_task> on 2024-05-17 00:00:00+00:00
[2024-10-18T13:36:08.425+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=17698) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:36:08.429+0000] {standard_task_runner.py:72} INFO - Started process 17721 to run task
[2024-10-18T13:36:08.427+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_3rd_task', 'scheduled__2024-05-17T00:00:00+00:00', '--job-id', '5579', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp6thz7ni1']
[2024-10-18T13:36:08.433+0000] {standard_task_runner.py:105} INFO - Job 5579: Subtask this_is_3rd_task
[2024-10-18T13:36:08.856+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2024-05-17T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:36:09.716+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-17T00:00:00+00:00'
[2024-10-18T13:36:09.723+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:36:09.866+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:36:09.869+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my third task and will run after task1 and at same time task2']
[2024-10-18T13:36:09.919+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:36:09.937+0000] {subprocess.py:93} INFO - Hello world, this is my third task and will run after task1 and at same time task2
[2024-10-18T13:36:09.943+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:36:10.103+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:36:10.105+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_3rd_task, run_id=scheduled__2024-05-17T00:00:00+00:00, execution_date=20240517T000000, start_date=20241018T133608, end_date=20241018T133610
[2024-10-18T13:36:10.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:36:10.990+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
