[2024-10-18T13:31:59.695+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:31:59.791+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2023-08-17T00:00:00+00:00 [queued]>
[2024-10-18T13:31:59.842+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2023-08-17T00:00:00+00:00 [queued]>
[2024-10-18T13:31:59.843+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:32:00.110+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_3rd_task> on 2023-08-17 00:00:00+00:00
[2024-10-18T13:32:00.173+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=14339) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:32:00.179+0000] {standard_task_runner.py:72} INFO - Started process 14360 to run task
[2024-10-18T13:32:00.178+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v4', 'this_is_3rd_task', 'scheduled__2023-08-17T00:00:00+00:00', '--job-id', '4760', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpb9k4_blh']
[2024-10-18T13:32:00.205+0000] {standard_task_runner.py:105} INFO - Job 4760: Subtask this_is_3rd_task
[2024-10-18T13:32:00.441+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v4.this_is_3rd_task scheduled__2023-08-17T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:32:00.906+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v4' AIRFLOW_CTX_TASK_ID='this_is_3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-17T00:00:00+00:00'
[2024-10-18T13:32:00.912+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:32:00.963+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:32:00.972+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my third task and will run after task1 and at same time task2']
[2024-10-18T13:32:00.995+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:32:01.009+0000] {subprocess.py:93} INFO - Hello world, this is my third task and will run after task1 and at same time task2
[2024-10-18T13:32:01.011+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:32:01.135+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:32:01.136+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v4, task_id=this_is_3rd_task, run_id=scheduled__2023-08-17T00:00:00+00:00, execution_date=20230817T000000, start_date=20241018T133159, end_date=20241018T133201
[2024-10-18T13:32:01.312+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:32:01.467+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
