[2024-10-18T13:21:35.952+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-18T13:21:35.978+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_3rd_task scheduled__2021-10-23T00:00:00+00:00 [queued]>
[2024-10-18T13:21:35.985+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.this_is_3rd_task scheduled__2021-10-23T00:00:00+00:00 [queued]>
[2024-10-18T13:21:35.986+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-18T13:21:36.028+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): this_is_3rd_task> on 2021-10-23 00:00:00+00:00
[2024-10-18T13:21:36.040+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1219) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-18T13:21:36.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'this_is_3rd_task', 'scheduled__2021-10-23T00:00:00+00:00', '--job-id', '1573', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp2ukag9ko']
[2024-10-18T13:21:36.052+0000] {standard_task_runner.py:72} INFO - Started process 1230 to run task
[2024-10-18T13:21:36.054+0000] {standard_task_runner.py:105} INFO - Job 1573: Subtask this_is_3rd_task
[2024-10-18T13:21:36.114+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.this_is_3rd_task scheduled__2021-10-23T00:00:00+00:00 [running]> on host ad4831ffc3d7
[2024-10-18T13:21:36.189+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sourabh' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='this_is_3rd_task' AIRFLOW_CTX_EXECUTION_DATE='2021-10-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-10-23T00:00:00+00:00'
[2024-10-18T13:21:36.192+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-18T13:21:36.221+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-18T13:21:36.222+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo Hello world, this is my third task and will run after task1 and at same time task2']
[2024-10-18T13:21:36.241+0000] {subprocess.py:86} INFO - Output:
[2024-10-18T13:21:36.244+0000] {subprocess.py:93} INFO - Hello world, this is my third task and will run after task1 and at same time task2
[2024-10-18T13:21:36.246+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-18T13:21:36.327+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-18T13:21:36.331+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=this_is_3rd_task, run_id=scheduled__2021-10-23T00:00:00+00:00, execution_date=20211023T000000, start_date=20241018T132135, end_date=20241018T132136
[2024-10-18T13:21:36.370+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-18T13:21:36.404+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-18T13:21:36.410+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
